language: python
virtualenv:
  system_site_packages: true
env:
  # global:
  #   - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"

install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
