language: python
env:
  global:
    - COVERAGE="true"
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"

install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
after_success:
    - if [[ $PYTHON_VERSION == "3.6*" ]]; then
          coveralls;
      fi
